<a href="https://colab.research.google.com/github/FidelCristopher/wpu-resolusi/blob/master/2802444044_Fidel_Cristopher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time
print(time.ctime())

Thu Feb  6 14:32:49 2025


In [ ]:
x = 1
x

1

In [ ]:
x = x + 1
x

2

In [ ]:
x = 1
y = x + 1
x = 2
y

2

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [ ]:
y = np.array([1, 4, 3])
y

array([1, 4, 3])

In [ ]:
x = np.array([[1, 4, 3], [9, 2, 7]])
x

array([[1, 4, 3],
       [9, 2, 7]])

In [ ]:
def my_adder(a, b, c):

 """
 function to sum three numbers
 Input: 3 numbers a, b, c
 Ouput: the sum of a, b, and c
 author:
 date:
 """

 #this is simulation
 out = a + b + c

 return out

In [ ]:
my_adder (1, 2, 3)

6

In [ ]:
def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = 'Heat'
  elif temp > desired_temp + 5:
    status = 'AC'
  else:
    status = 'Off'
  return status


In [ ]:
status = my_thermo_stat(65,75)
print(status)

Heat


In [ ]:
status = my_thermo_stat(75, 65)
print(status)

AC


In [ ]:
status = my_thermo_stat(65, 63)
print(status)

Off


MODUL 1 (GRADING SYSTEM)

In [ ]:
def login():
    username = "Fidel Cristopher"
    password = "Bn123"

    while True:
        user_input = input("Masukkan Username: ")
        pass_input = input("Masukkan Password: ")

        if user_input == username and pass_input == password:
            print("Login Berhasil!\n")
            break
        else:
            print("Username atau password salah. Coba lagi.\n")

def calculate(uas, uts, asg):
    return (0.5 * uas) + (0.3 * uts) + (0.2 * asg)

def determine_grade(score):
    if 90 <= score <= 100:
        return "A"
    elif 85 <= score < 90:
        return "A-"
    elif 80 <= score < 85:
        return "B+"
    elif 75 <= score < 80:
        return "B"
    elif 70 <= score < 75:
        return "B-"
    elif 65 <= score < 70:
        return "C"
    elif 50 <= score < 65:
        return "D"
    elif 0 <= score < 50:
        return "E"
    else:
        return "Invalid Score"

def main():
    login()

    nama_siswa = input("Masukkan nama siswa: ")
    uas = int(input("Masukkan Nilai UAS: "))
    uts = int(input("Masukkan Nilai UTS: "))
    asg = int(input("Masukkan Nilai Assignment: "))

    final_score = calculate(uas, uts, asg)
    grade = determine_grade(final_score)

    print("==========================================")
    print(f"Nama Siswa: {nama_siswa}")
    print(f"Final Score: {final_score:.2f}")
    print(f"Grade: {grade}")

if __name__ == "__main__":
    main()


Masukkan Username: Fidel Cristopher
Masukkan Password: Bn123
Login Berhasil!

Masukkan nama siswa: Budi
Masukkan Nilai UAS: 90
Masukkan Nilai UTS: 75
Masukkan Nilai Assignment: 98
Nama Siswa: Budi
Final Score: 87.10
Grade: A-
